PATH_CONST:
  OUTPUTPATH: tmp/
  ANALYSISPATH: ''

PROCESSING_CONST:
  BIN_BLOCK_SIZE: 5
  BIN_CONST: 30
  MARGIN_CONST: 0.05
  AVG_ROW_SIZE: 100
  STRUCT_SIZE: [5, 10]
  AVG_LINE_HEIGHT: 150
  DILET_ITER: 2