PATH_CONST:
  OUTPUTPATH: tmp/
  ANALYSISPATH: ''

PROCESSING_CONST:
  BIN_BLOCK_SIZE: 5
  BIN_CONST: 30
  MARGIN_CONST: 0.05
  AVG_ROW_SIZE: 100
  STRUCT_SIZE: [30, 3]
  DILET_FOR_HOUGH: [30, 3]
  HOUGH_MAX_CELL: 200
  AVG_LINE_HEIGHT: 150
  DILET_ITER: 1
  AVG_LINE_GAP: 10